format="""
$directory$git_branch$git_state$git_status$kubernetes
$jobs$character\
"""

add_newline = true

[character]
success_symbol = "ğŸª²"
error_symbol = "[ğŸ›](bold red)"

[directory]
style = "purple"

[git_branch]
style = "cyan"


[git_status]
format = " [($staged)](yellow)[($untracked)](blue)[($deleted)](red)[($modified)](green) "
conflicted = "ğŸ˜³ "
untracked  = "ğŸ¦–"
modified   = "ğŸ¥"
staged     = "ğŸŒ±"
deleted    = "ğŸ”´"

[jobs]
symbol = "â—"
style = "blue"
format = "[$number$symbol]($style) "

[kubernetes]
disabled = false
symbol = "â˜¸ "
format = '($symbol)[$context](bold green) â›µ [$namespace](bold yellow)'
